function [methodinfo,structs,enuminfo,ThunkLibName]=dxl_prototype
%DXL_PROTOTYPE Create structures to define interfaces found in 'dynamixel_sdk'.

%This function was generated by loadlibrary.m parser version  on Sun Feb  1 12:10:12 2026
%perl options:'dynamixel_sdk.i -outfile=dxl_prototype.m -thunkfile=dxl_x64_c_thunk_pcwin64.c -header=dynamixel_sdk.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'dxl_x64_c_thunk_pcwin64');
methodinfo=fcns;